services:
  server-db:
    image: postgres:16.3
    env_file:
      - path: .server.env
        required: true
    environment:
      POSTGRES_DB: ${SERVER_DB_NAME} # The name of your database instance
      POSTGRES_USER: ${SERVER_DB_USER} # Username
      POSTGRES_PASSWORD: ${SERVER_DB_PASSWORD} # Password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
    ports:
      - ${SERVER_DB_PORT}:${SERVER_DB_PORT} # Postgres port

volumes:
  postgres_data: # This named volume will store the PostgreSQL database files
